apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-inventoryservice
  name: new-inventoryservice
  namespace: seat-1
spec:
  ports:
  - name: http
    nodePort: 30073
    port: 5073
    protocol: TCP
    targetPort: 5073
  selector:
    app: new-inventoryservice
  type: NodePort
