apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-notificationservice
  name: new-notificationservice
  namespace: seat-1
spec:
  ports:
  - name: http
    nodePort: 30072
    port: 5072
    protocol: TCP
    targetPort: 5072
  selector:
    app: new-notificationservice
  type: NodePort
