apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentservice
  name: paymentservice
  namespace: seat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - env:
        - name: EXTERNAL_PAYMENT_ENDPOINT
          value: https://pay-api.partner.example.com
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        image: ttl.sh/paymentservice-apm-20260528-1956:24h
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
            service: ""
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: server
        ports:
        - containerPort: 50051
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
            service: ""
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
