apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-riskcontrolservice
  name: new-riskcontrolservice
  namespace: seat-1
spec:
  ports:
  - name: http
    nodePort: 30071
    port: 5071
    protocol: TCP
    targetPort: 5071
  selector:
    app: new-riskcontrolservice
  type: NodePort
