apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: new-riskcontrolservice
  name: new-riskcontrolservice
  namespace: seat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-riskcontrolservice
  template:
    metadata:
      labels:
        app: new-riskcontrolservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "5071"
        - name: CURRENCY_SERVICE_ADDR
          value: "__TENCENT_IP__:30009"
        image: docker.io/library/new-riskcontrolservice:v1.0
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5071
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: server
        ports:
        - containerPort: 5071
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5071
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
