apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-userbehaviorservice
  name: new-userbehaviorservice
  namespace: seat-1
spec:
  ports:
  - name: http
    nodePort: 30074
    port: 5074
    protocol: TCP
    targetPort: 5074
  selector:
    app: new-userbehaviorservice
  type: NodePort
