apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: seat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "__TENCENT_IP__:30008"
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: PAYMENT_SERVICE_ADDR
          value: "__AWS_IP__:30051"
        - name: EMAIL_SERVICE_ADDR
          value: "__TENCENT_IP__:30010"
        - name: CURRENCY_SERVICE_ADDR
          value: "__TENCENT_IP__:30009"
        - name: CART_SERVICE_ADDR
          value: "__TENCENT_IP__:30007"
        - name: ORDER_SERVICE_ADDR
          value: "__AWS_IP__:30070"
        - name: ORDER_STORE_ADDR
          value: new-orderstore:5080
        - name: PRODUCT_SERVICE_ADDR
          value: "__TENCENT_IP__:30007"
        image: checkout-apm-direct:20260528
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          grpc:
            port: 5050
            service: ""
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: server
        ports:
        - containerPort: 5050
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 5050
            service: ""
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
