apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-orders
  namespace: seat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-orders
  template:
    metadata:
      labels:
        app: mysql-orders
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "sztu172712"
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        hostPath:
          path: /data/mysql-orders
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-orders
  name: mysql-orders
  namespace: seat-1
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-orders
  type: ClusterIP
