apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: seat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis-cart:6379
        image: registry.k8s.io/cartservice:v0.10.5
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 7070
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
