apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: seat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - image: registry.k8s.io/emailservice:v0.10.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/true
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: server
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/true
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
