apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: seat-1
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30010
  selector:
    app: emailservice
  type: NodePort
