apiVersion: v1
kind: Service
metadata:
  name: new-gatewayservice
  namespace: seat-1
spec:
  ports:
  - name: tcp
    port: 5075
    protocol: TCP
    targetPort: 5075
    nodePort: 30076
  selector:
    app: new-gatewayservice
  type: NodePort
